name: hotaal
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  image_picker:
  firebase_messaging: ^5.1.5
  dio: any
  sqflite:
  flutter_offline: ^0.2.4+1



  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter_swiper: ^1.1.4
  badges: ^1.1.0
  flutter_charts: ^0.1.10
  flutter_webview_plugin: ^0.3.0+2
  waveprogressbar_flutter: ^0.1.2
  shared_preferences: ^0.5.3+4
  provide: ^1.0.2
  flutter_screenutil: ^0.6.0
  flutter_calendar: ^0.0.8
  fl_chart: ^0.3.4
  speech_recognition: ^0.3.0+1
  qrcode_reader: ^0.4.4
  intl: ^0.15.0
  splashscreen: ^1.2.0
  vibrate: ^0.0.4
  barcode_scan: any
  ping_discover_network: ^0.2.0+1
  overlay_support: ^1.0.1
  path_provider: ^1.3.1
  flutter_secure_storage: ^3.3.1+1
  awesome_dialog: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/DancingScript-Regular.ttf
    - family: Title
      fonts:
        - asset: assets/VarelaRound-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - image/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
